name: Retraining flow

on: [push]

jobs:
  retraining:
    runs-on: ubuntu-latest
    env:
      REPORT_NAME: ${{ secrets.REPORT_NAME }}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install poetry
        uses: knowsuchagency/poetry-install@v2

      - name: Run training
        run: |
          poetry run python run_training.py

      - name: Upload deepcheck report
        uses: actions/upload-artifact@v3
        with:
          name: Upload report
          path: ${{ secrets.REPORT_NAME }}
